---
- name: Install HTTP server ubuntu
  hosts: n2
  become: yes
 
  tasks:
  - name: Install Apache2
    yum:
      name: apache2
      state: present
  
  - name: Start Apache2
    service:
      name: apache2
      state: started
  
  - name: Enabled Apache2
    service:
      name: apache2
      enabled: yes
...