---
- name: Variables Demo
  hosts: g1
  become: yes
  vars:
    myusername: siri
 
  tasks:
  - name: Update Dynamic Page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic.html
...